### ISSUE TITLE
The model's docker image is not working as expected

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/eos4qda#5]
Current log (from the eos-tmp folder's run.log) for a single input run:
```bash
Traceback (most recent call last):
  File "/root/bentoml/repository/eos4qda/20240409100658_9CD2D1/eos4qda/artifacts/framework/code/main.py", line 33, in <module>
    output = sample(smi)
  File "/root/bentoml/repository/eos4qda/20240409100658_9CD2D1/eos4qda/artifacts/framework/code/main.py", line 21, in sample
    return sampler.sample()
  File "/root/eos/repository/eos4qda/20240409100658_9CD2D1/eos4qda/artifacts/framework/code/biased_sampler.py", line 169, in sample
    s for s in list(set(self._sample_single())) if "*" not in s
  File "/root/eos/repository/eos4qda/20240409100658_9CD2D1/eos4qda/artifacts/framework/code/biased_sampler.py", line 118, in _sample_single
    with open(self.output_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmphguaaoo_/output.smi'
root@d0821ee56636:/tmp# ls tmphguaaoo_/
cur_frags.smi  input_frags.smi  log.txt  query.smi
```

**Comment by DhanshreeA** [comment]
This has been happening because the model's installation is very different from other models in the hub. It uses some OCAML dependencies that get lost during the multi stage build. We have recently added [support](https://github.com/ersilia-os/ersilia/issues/1104) for falling back to the older builds if the new build does not work.

**Comment by DhanshreeA** [comment]
This is fixed by introducing V1 (single stage) and V2 (multi stage builds). And we are using V1 for this.
